[package]
name = "sosecrets-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = 'test_compile_fail_one'
# path = "trybuild_tests/test_compile_fail_one.rs"

# [[bin]]
# name = 'test_compile_fail_two'
# path = "trybuild_tests/test_compile_fail_two.rs"

[dependencies]
typenum = "1.17.0"
zeroize = { version = "1.6.0" }

[dev-dependencies]
trybuild = "1.0.85"
